sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: meeting_room_db
    username: root
    password: a912812618
  redis:
    host: localhost
    port: 6379
    database: 0