sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: a912812618
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5t9jZi4ReiaXpDNB4srr
    accessKeySecret: xlgJdb8APPwYFSz0AVrEwqD5xlv6Eg
    bucketName: web-fengyi-tlias
  redis:
    host: localhost
    port: 6379
    database: 0
